### ISSUE TITLE
Moving from jade to pug

### ISSUE THREAD

**Issue by ghost** [ahmadnassri/node-metalsmith-pug#39]
As [this issue](https://github.com/pugjs/pug/issues/2184) mentions jade is changing to pug. Are there any plans to use pug instead of jade(now or in the future)?

**Comment by ahmadnassri** [comment]
indeed, we should update the dependencies ...

**Comment by Surgo** [comment]
hey hey

**Comment by Surgo** [comment]
Renaming a published module are not supported by npm.
Can I fork and publish `metalsmith-pug`?

**Comment by ahmadnassri** [comment]
I'll look into this today

**Comment by ahmadnassri** [comment]
@Surgo I'm ready to merge, deprecate and publish, we also have to make a PR on https://github.com/metalsmith/metalsmith.io (I can do that once the PR is merged, this acts as a note to self)

**Comment by ahmadnassri** [comment]
@luksprog @Surgo all done! `metalsmith-pug` is now live!

**Comment by ahmadnassri** [comment]
ref for metalsmith.io site: https://github.com/metalsmith/metalsmith.io/pull/180
