### ISSUE TITLE
Pug is out of date

### ISSUE THREAD

**Issue by zommerfelds** [ahmadnassri/node-metalsmith-pug#79]
I'm getting a warning on my repo because `metailsmith-pug` is using a vulnerable version of pug. Can we upgrade to version `3`?

I tried to do this but I couldn't figure out how this repo generates the output file. Running `npm run compile` doesn't seem to create a `lib` directory.

**Comment by ahmadnassri** [comment]
updated in [3.0.0](https://github.com/ahmadnassri/node-metalsmith-pug/compare/v2.0.2...v3.0.0)
